title: Self-Service BI Blog
email: kavasi.mihaly@outlook.com
description: >-
  A practical guide to Self-Service Business Intelligence using Microsoft's Azure and Power BI. 
  Explore best practices, overcome adoption challenges, and discover how to empower decision makers 
  with data. Written by a practicing BI consultant sharing real-world strategies to help organizations 
  unlock the full value of their data.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://KavasiMihaly.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# Tell Jekyll to process files in the _pages directory
include: ["_pages"]

# Pagination settings
paginate: 5
paginate_path: "/page:num/"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - README.md
